print('HELLO!!')
NAME=input('YOUR NAME PLS:')
AGE=int(input('YOUR AGE PLS:'))

AGEMONTH=AGE*12
AGEWEEK=AGE*4
AGEDAY=AGE*365
AGEHOURS=AGE*8760
AGEMINUTES=AGEHOURS*60
AGESECONDS=AGEMINUTES*60 

print('YOUR AGE IN MONTHS IS:', AGEMONTH)
print('YOUR AGE IN WEEKS IS:', AGEWEEK)
print('YOUR AGE IN DAYS IS:', AGEDAY)
print('YOUR AGE IN HOURS IS:', AGEHOURS)
print('YOUR AGE IN MINUTES IS:', AGEMINUTES)
print('YOUR AGE IN SECONDS IS:', AGESECONDS)



