print('PLS PUT YOUR COMPLETE NAME')
COMPLETE=input()
print('YOUR COMPLETE NAME IS:',COMPLETE )

print('IN WHICH GROUP AND GRADE ARE YOU?')
GRADEGROUP=input()
print('YOU ARE IN:',GRADEGROUP)

print('WHICH IS YOUR FAV FOOD?')
FAVFOOD =input()
print('YOUR FAV FOOD IS:',FAVFOOD )

print('SOMETHING YOU WANT TO TELL?')
X=input()
print('SOMETHING YOU WANT TO TELL TO MR ROBERT IS:', X)
